package:
  name: ann
  version: 1.1.2

source:
  git_url: https://github.com/EUPSForge/ann.git
  git_tag: v1.1.2

#requirements:
#  build:
#    - python 2.7.*
#    - numpy ==1.9
#  run:
#    - python 2.7.*
#    - numpy >=1.9

#test:
#  # Python imports
#  imports:
#    - Polygon
#    - Polygon.IO
#    - Polygon.Shapes
#    - Polygon.Utils

about:
  home: https://github.com/EUPSForge/ann
